package repo_room_facility

import (
	"booking-room-app/entity"
	"booking-room-app/shared/model"

	"github.com/stretchr/testify/mock"
)

type RoomFacilityRepoMock struct {
	mock.Mock
}

func (m *RoomFacilityRepoMock) CreateRoomFacility(payload entity.RoomFacility, newFacilityQuantity int) (entity.RoomFacility, int, error) {
	/* no need to send argument anymore because payload already send by CreateRoomFacility function,
	   and newFacilityQuantity automatically generated by actual code
	*/
	// args := m.Called(payload, newFacilityQuantity)
	args := m.Called()
	return args.Get(0).(entity.RoomFacility), args.Int(1), args.Error(2)
}

func (m *RoomFacilityRepoMock) GetQuantityFacilityByID(id string) (int, int, error) {
	// args := m.Called(id)
	args := m.Called()
	return args.Int(0), args.Int(1), args.Error(2)
}

func (m *RoomFacilityRepoMock) GetRoomFacilityById(id string) (entity.RoomFacility, int, error) {
	//args := m.Called(id)
	args := m.Called()
	return args.Get(0).(entity.RoomFacility), args.Int(1), args.Error(2)
}

func (m *RoomFacilityRepoMock) ListRoomFacility(page int, size int) ([]entity.RoomFacility, model.Paging, error) {
	//args := m.Called(page, size)
	args := m.Called()
	return args.Get(0).([]entity.RoomFacility), args.Get(1).(model.Paging), args.Error(2)
}

func (m *RoomFacilityRepoMock) UpdateRoomFacility(payload entity.RoomFacility, newFacilityQuantity int) (entity.RoomFacility, int, error) {
	//args := m.Called(payload, newFacilityQuantity)
	args := m.Called()
	return args.Get(0).(entity.RoomFacility), args.Int(1), args.Error(2)
}
